name: Test Docker upload

on:
  workflow_dispatch: null


jobs:
  build-and-upload:
    outputs:
      digest: ${{ steps.build-docker.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # pin@v2.2.1

      - name: Login to Docker Hub
        id: docker-login
        # See unresolved bug https://github.com/actions/runner/issues/1483
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.JFROG_USERNAME }}  # because on my fork, JFROG_USERNAME is really for dockerhub
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Build and push docker image
        id: build-docker
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # pin@v3.2.0
        with:
          context: docker_test
          file: docker_test/Dockerfile
          tags: docker.io/janheidbrinktng/dockertest:bar
          push: true

      - run: echo "Image digest is \`${{ steps.build-docker.outputs.digest }}\`" >> $GITHUB_STEP_SUMMARY

  print_digest:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - run: echo ${{ needs.build-and-upload.outputs.digest }}

  run:
    needs: build-and-upload
    uses: jheidbrink/magma/.github/workflows/test_docker_download_by_digest.yml@master
    with:
      digest: ${{ needs.build-and-upload.outputs.digest }}