name: Test Docker download by digest

on:
  workflow_dispatch:
    inputs:
      digest:
        type: string
        required: true
  workflow_call:
    inputs:
      digest:
        type: string
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
      - run: echo ${{ inputs.digest }}
      - run: docker run docker.io/janheidbrinktng/dockertest@${{ inputs.digest }} echo hello